name: roavapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  flutter_svg: ^0.17.0
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.30
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  intl: ^0.16.1
  permission_handler: ^5.0.1+1
  table_calendar: ^2.2.3
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/raster/
   - assets/images/svg/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
        - asset: assets/fonts/Ubuntu-M.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-B.ttf
          weight: 700
